apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  annotations:
    zone: fss
  labels:
    app: dp-behovsakkumulator
    team: teamdagpenger
  name: dp-behovsakkumulator
  namespace: default
spec:
  image: {{ image }}
  liveness:
    path: /isalive
  readiness:
    path: /isready
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    max: 6
    min: 1
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  vault:
    enabled: true
    paths:
      - kvPath: "/serviceuser/data/dev/srvdp-behovsakk"
        mountPath: "/var/run/secrets/nais.io/service_user/"
  env:
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
    - name: KAFKA_CONSUMER_GROUP_ID
      value: dp-behovsakkumulator-v1
    - name: KAFKA_RAPID_TOPIC
      value: privat-dagpenger-behov-v1
  
