name: ktlint
on: [push]

jobs:
  code-style-violations:
    name: Check coding style violations
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: musichin/ktlint-check@v2